version: '2'
services:
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - cluster.name=scrp-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .esdata/:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"


 kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    external_links:
      - elasticsearch
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - "5601:5601"

 # logstash:
 #    image: docker.elastic.co/logstash/logstash:7.0.0
 #    links:
 #      - elasticsearch
 #    volumes:
 #      - "./logstash/conf.d:/usr/share/logstash/pipeline"

volumes:
    scrp-elastic-stack:
        driver: local

networks:
  default:
    external:
      name: projectmonarch_default
