version: "2"
services:
    scipy-notebook:
        image: jupyter/base-notebook:python-3.7.3
        volumes:
            - ../:/home/jovyan/work
        ports:
            - "8888:8888"
        

networks:
  default:
    external:
      name: projectmonarch_default
